export interface Job {
  id: string
  title: string
  company: string
  companyInitials: string
  companyColor: string
  location: string
  jobType: 'Full-time' | 'Part-time' | 'Internship' | 'Contract'
  salaryMin: number
  salaryMax: number
  experience: string
  summary: string
  fullDescription: string
  requirements: string[]
  companyInfo: string
  aiSummary: string[]
  matchScore: number
  postedDays: number
  applyLink: string
}

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    company: 'TechNova Solutions',
    companyInitials: 'TN',
    companyColor: 'bg-purple-600',
    location: 'Bangalore',
    jobType: 'Full-time',
    salaryMin: 18,
    salaryMax: 25,
    experience: '3-5 years',
    summary: 'Build cutting-edge React applications with TypeScript. Work on scalable design systems and collaborate with cross-functional teams.',
    fullDescription: 'We are looking for a Senior Frontend Engineer to join our growing team. You will be responsible for building and maintaining our core product interfaces, working closely with designers and backend engineers to deliver exceptional user experiences. This role involves architecting scalable frontend solutions, mentoring junior developers, and contributing to our design system.',
    requirements: ['5+ years of React experience', 'TypeScript proficiency', 'Experience with state management (Redux/Zustand)', 'Strong CSS/Tailwind skills', 'CI/CD experience'],
    companyInfo: 'TechNova Solutions is a fast-growing SaaS company building the future of enterprise collaboration tools. With 200+ employees across 3 continents, we serve Fortune 500 clients.',
    aiSummary: ['Strong React/TypeScript role with design system focus', 'Collaborative environment with cross-functional teams', 'Competitive salary with equity options'],
    matchScore: 92,
    postedDays: 2,
    applyLink: 'https://example.com/apply',
  },
  {
    id: '2',
    title: 'Backend Developer',
    company: 'CloudScale Inc',
    companyInitials: 'CS',
    companyColor: 'bg-blue-600',
    location: 'Remote',
    jobType: 'Full-time',
    salaryMin: 15,
    salaryMax: 22,
    experience: '3-5 years',
    summary: 'Design and implement microservices architecture. Work with Node.js, PostgreSQL, and AWS to build reliable systems.',
    fullDescription: 'Join our backend team to build and scale our cloud infrastructure. You will work on designing microservices, optimizing database performance, and ensuring system reliability. We use modern DevOps practices and believe in infrastructure as code.',
    requirements: ['Node.js/Python expertise', 'PostgreSQL/MongoDB experience', 'AWS/GCP knowledge', 'Docker & Kubernetes', 'API design skills'],
    companyInfo: 'CloudScale Inc provides cloud infrastructure solutions to startups and enterprises. We process millions of requests daily and are backed by top-tier VCs.',
    aiSummary: ['Focus on microservices and cloud infrastructure', 'Remote-first culture with flexible hours', 'Growth opportunity in scaling systems'],
    matchScore: 85,
    postedDays: 5,
    applyLink: 'https://example.com/apply',
  },
  {
    id: '3',
    title: 'UI/UX Designer',
    company: 'DesignLab Studio',
    companyInitials: 'DL',
    companyColor: 'bg-pink-600',
    location: 'Mumbai',
    jobType: 'Full-time',
    salaryMin: 10,
    salaryMax: 16,
    experience: '1-3 years',
    summary: 'Create beautiful, intuitive interfaces for web and mobile applications. Lead user research and prototype designs.',
    fullDescription: 'We are seeking a talented UI/UX Designer to join our creative team. You will be responsible for conducting user research, creating wireframes and prototypes, and delivering pixel-perfect designs. Experience with design systems and accessibility standards is a plus.',
    requirements: ['Figma/Sketch proficiency', 'User research experience', 'Prototyping skills', 'Design system knowledge', 'Portfolio required'],
    companyInfo: 'DesignLab Studio is a boutique design agency working with startups and Fortune 500 companies to create memorable digital experiences.',
    aiSummary: ['Creative role with end-to-end design ownership', 'Work on diverse client projects', 'Strong emphasis on user research'],
    matchScore: 78,
    postedDays: 1,
    applyLink: 'https://example.com/apply',
  },
  {
    id: '4',
    title: 'DevOps Engineer',
    company: 'InfraCore Systems',
    companyInitials: 'IC',
    companyColor: 'bg-emerald-600',
    location: 'Hyderabad',
    jobType: 'Full-time',
    salaryMin: 14,
    salaryMax: 20,
    experience: '3-5 years',
    summary: 'Manage CI/CD pipelines, Kubernetes clusters, and cloud infrastructure. Automate everything.',
    fullDescription: 'Join our DevOps team to build and maintain our infrastructure. You will work on automating deployments, managing Kubernetes clusters, and ensuring high availability of our services. Experience with monitoring tools and incident response is essential.',
    requirements: ['Kubernetes expertise', 'Terraform/Ansible', 'AWS/Azure certified', 'Linux administration', 'Monitoring tools (Prometheus/Grafana)'],
    companyInfo: 'InfraCore Systems provides managed infrastructure services to enterprises. We manage 500+ servers and have 99.99% uptime SLA.',
    aiSummary: ['Infrastructure automation focus', 'Work with cutting-edge DevOps tools', 'Enterprise-level scale and challenges'],
    matchScore: 88,
    postedDays: 3,
    applyLink: 'https://example.com/apply',
  },
  {
    id: '5',
    title: 'Product Manager',
    company: 'StartupX',
    companyInitials: 'SX',
    companyColor: 'bg-orange-600',
    location: 'Delhi',
    jobType: 'Full-time',
    salaryMin: 20,
    salaryMax: 30,
    experience: '5+ years',
    summary: 'Lead product strategy and roadmap for our flagship product. Work closely with engineering and design teams.',
    fullDescription: 'We are looking for an experienced Product Manager to own our core product. You will define product vision, prioritize features, and work with stakeholders to deliver value to customers. Strong analytical skills and customer empathy are essential.',
    requirements: ['5+ years PM experience', 'Technical background preferred', 'Data-driven mindset', 'Excellent communication', 'Startup experience'],
    companyInfo: 'StartupX is a Series B funded fintech startup revolutionizing digital payments in India. We have 2M+ active users and growing 30% MoM.',
    aiSummary: ['Leadership role with strategic impact', 'Fast-paced fintech environment', 'High growth potential with equity'],
    matchScore: 72,
    postedDays: 7,
    applyLink: 'https://example.com/apply',
  },
  {
    id: '6',
    title: 'Data Scientist',
    company: 'AI Nexus Labs',
    companyInitials: 'AN',
    companyColor: 'bg-violet-600',
    location: 'Bangalore',
    jobType: 'Full-time',
    salaryMin: 16,
    salaryMax: 24,
    experience: '3-5 years',
    summary: 'Build ML models for recommendation systems and predictive analytics. Work with large datasets.',
    fullDescription: 'Join our data science team to build machine learning models that power our product recommendations. You will work with terabytes of data, experiment with different algorithms, and deploy models to production. Strong Python and ML framework experience required.',
    requirements: ['Python/R proficiency', 'ML frameworks (TensorFlow/PyTorch)', 'SQL expertise', 'Statistics background', 'Communication skills'],
    companyInfo: 'AI Nexus Labs is an AI-first company building intelligent automation solutions. Our models process 10M+ predictions daily.',
    aiSummary: ['Work on production ML systems', 'Large-scale data processing', 'Research-oriented environment'],
    matchScore: 82,
    postedDays: 4,
    applyLink: 'https://example.com/apply',
  },
  {
    id: '7',
    title: 'Mobile Developer (React Native)',
    company: 'AppForge',
    companyInitials: 'AF',
    companyColor: 'bg-cyan-600',
    location: 'Pune',
    jobType: 'Contract',
    salaryMin: 8,
    salaryMax: 12,
    experience: '1-3 years',
    summary: 'Build cross-platform mobile apps using React Native. Work on both iOS and Android platforms.',
    fullDescription: 'We are looking for a React Native developer to help build our mobile applications. You will work on feature development, bug fixes, and performance optimization. Experience with native modules and app store deployment is a plus.',
    requirements: ['React Native experience', 'JavaScript/TypeScript', 'iOS/Android basics', 'REST API integration', 'App Store/Play Store knowledge'],
    companyInfo: 'AppForge is a mobile-first development agency building apps for startups and enterprises. We have shipped 50+ apps with 10M+ downloads.',
    aiSummary: ['Cross-platform mobile development', '6-month contract with extension option', 'Diverse project exposure'],
    matchScore: 75,
    postedDays: 2,
    applyLink: 'https://example.com/apply',
  },
  {
    id: '8',
    title: 'Software Engineering Intern',
    company: 'CodeMentor Inc',
    companyInitials: 'CM',
    companyColor: 'bg-rose-600',
    location: 'Remote',
    jobType: 'Internship',
    salaryMin: 0.5,
    salaryMax: 1,
    experience: 'Fresher',
    summary: 'Learn and grow as a software engineer. Work on real projects with mentorship from senior engineers.',
    fullDescription: 'Join our 6-month internship program designed for fresh graduates. You will work on real projects, receive mentorship from experienced engineers, and have the opportunity to convert to full-time. We provide a structured learning path and regular feedback.',
    requirements: ['CS/Engineering degree', 'Basic programming knowledge', 'Eagerness to learn', 'Good communication', 'Problem-solving skills'],
    companyInfo: 'CodeMentor Inc is an ed-tech company focused on developer education. Our platform has trained 100K+ developers worldwide.',
    aiSummary: ['Structured internship program', 'Strong mentorship and learning', 'Full-time conversion opportunity'],
    matchScore: 95,
    postedDays: 1,
    applyLink: 'https://example.com/apply',
  },
  {
    id: '9',
    title: 'QA Engineer',
    company: 'QualityFirst Tech',
    companyInitials: 'QF',
    companyColor: 'bg-amber-600',
    location: 'Hyderabad',
    jobType: 'Part-time',
    salaryMin: 4,
    salaryMax: 7,
    experience: '1-3 years',
    summary: 'Ensure software quality through manual and automated testing. Write test cases and automate test suites.',
    fullDescription: 'We are looking for a part-time QA Engineer to help ensure the quality of our software products. You will write test cases, execute manual tests, and help automate our test suite. Experience with Selenium/Cypress and API testing is preferred.',
    requirements: ['Testing methodologies', 'Automation tools (Selenium/Cypress)', 'API testing', 'Bug tracking tools', 'Attention to detail'],
    companyInfo: 'QualityFirst Tech provides QA services to software companies. We have helped 200+ companies improve their software quality.',
    aiSummary: ['Part-time role with flexible hours', 'Mix of manual and automated testing', 'Work with multiple client projects'],
    matchScore: 68,
    postedDays: 6,
    applyLink: 'https://example.com/apply',
  },
]
